import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-main-content',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './main-content.component.html',
  styleUrl: './main-content.component.css'
})
export class MainContentComponent {
  items = [
    { name: 'Assignment3.ipynb', type: 'file', modified: 'Mar 30, 2024' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    { name: 'COVID-1583.png', type: 'image', modified: '2:46 PM' },
    
    // ... add more items as needed
  ];
}
